jenkinsdata:
  build: jenkins-data
jenkinsmaster:
  build: jenkins-master
  volumes_from:
    - jenkinsdata
  ports:
    - "50000:50000"
#jenkinsnginx:
#build: jenkins-nginx
#ports:
#- "80:80"
#links:
#- jenkinsmaster:jenkins-master

# gitlab
# elasticsearch
# appium
# kibana
# sonarqube
# versioneye
# graphite
# dockergc
# jenkinsslave
# cadvisor
# gather metrics
# graphana
# influxdb
# Zabbix
# Chef Server
# cadvisor
# openldap(?)
#
